services:
  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:9.2.4'
    environment:
      - 'ELASTIC_PASSWORD=secret'
      - 'discovery.type=single-node'
      - 'xpack.security.enabled=false'
    ports:
      - '9200:9200'
      - '9300:9300'
  kibana:
    image: 'kibana:9.2.4'
    ports:
      - 5601:5601
  rabbitmq:
    image: 'rabbitmq:4.2.3'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=secret'
      - 'RABBITMQ_DEFAULT_USER=myuser'
    ports:
      - '5672'
