spring:
  application:
    name: discord-messages-archivizer
  elasticsearch:
    uris: http://elasticsearch:9200
  rabbitmq:
    host: rabbitmq
    username: ${RABBITMQ_DEFAULT_USER}
    password: ${RABBITMQ_DEFAULT_PASS}
app:
  discord-bot-token: ${DISCORD_BOT_TOKEN_MESSAGES_ARCHIVIZER}
  queue-name: discord-messages-archivizer-queue
  queue-prefetch-count: 2
  thread-pool-size-for-messages-handler: 2
  index-name: discord-message
logging:
  level:
    com:
      github:
        arkadiusz97:
          discordmessagesarchivizer: DEBUG
